# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "seo-app"
client_id = "26941ddb76eaac773f4795acb2feb832"
application_url = "https://scientific-eligible-transportation-end.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://scientific-eligible-transportation-end.trycloudflare.com/auth/callback",
  "https://scientific-eligible-transportation-end.trycloudflare.com/auth/shopify/callback",
  "https://scientific-eligible-transportation-end.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "seo-app-testing.myshopify.com"
